name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-basic-validation: # The reusable workflow can be found here: https://github.com/actions/reusable-workflows/blob/main/.github/workflows/basic-validation.yml
    name: Basic validation
    uses: actions/reusable-workflows/.github/workflows/basic-validation.yml@main