name: Tests
on:
  push:
    branches:
      - main
  pull_request: null
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
